name: python-heima-rga-agent
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - annotated-types=0.6.0
  - anyio=4.12.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - colorama=0.4.6
  - distro=1.9.0
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - idna=3.11
  - jiter=0.12.0
  - libexpat=2.7.4
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libzlib=1.3.1
  - openai=2.14.0
  - openssl=3.5.5
  - packaging=25.0
  - pip=26.0.1
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - python=3.13.12
  - python_abi=3.13
  - setuptools=80.10.2
  - sniffio=1.3.1
  - sqlite=3.51.2
  - tk=8.6.15
  - tqdm=4.67.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2026a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.8.2
  - zlib=1.3.1
